// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Error: typeof import('./src/components/Form/Error.vue')['default']
    FormGroup: typeof import('./src/components/Form/FormGroup.vue')['default']
    Input: typeof import('./src/components/Form/Input.vue')['default']
    Label: typeof import('./src/components/Form/Label.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
  }
}
