// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FormError: typeof import('./src/components/Form/FormError.vue')['default']
    FormForgotPassword: typeof import('./src/components/Form/FormForgotPassword.vue')['default']
    FormGroup: typeof import('./src/components/Form/FormGroup.vue')['default']
    FormInput: typeof import('./src/components/Form/FormInput.vue')['default']
    FormLabel: typeof import('./src/components/Form/FormLabel.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
